version: '3'
services:
  magento:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magento
    volumes:
      - ./magento:/var/www/html
    depends_on:
      - mariadb
      - elasticsearch
      - redis
      - rabbitmq
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_DATABASE=magento
      - MARIADB_USER=magento
      - MARIADB_PASSWORD=magento
      - ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_LANGUAGE=pl_PL
      - MAGENTO_CURRENCY=PLN
      - MAGENTO_TIMEZONE=Europe/Warsaw
      - MAGENTO_ADMIN_USER=admin
      - MAGENTO_ADMIN_PASSWORD=admin123
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=User
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    networks:
      - magento-network

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - magento-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./magento:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - magento
    networks:
      - magento-network

  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - magento-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - magento-network

  varnish:
    image: varnish:stable
    container_name: varnish
    ports:
      - "8080:80"
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    depends_on:
      - nginx
    networks:
      - magento-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - magento-network

networks:
  magento-network:
    driver: bridge

volumes:
  mariadb_data:
  elasticsearch_data:
  redis_data:
  rabbitmq_data: 